### ISSUE TITLE
PseudoTopProducer crash report

### ISSUE THREAD

**Issue by jhgoh** [vallot/CATTools#430]
PseudoTopProducer crashes

https://cmsweb.cern.ch/scheddmon/0109/cms1333/160209_213620:jlee_crab_v7-6-2_TT_TuneEE5C_13TeV-amcatnlo-herwigpp/job_out.7.1.txt

```
== CMSSW: %MSG
== CMSSW: %MSG-w DataNotFound:  PseudoTopProducer:pseudoTop 09-Feb-2016 17:22:10 PST  Run: 1 Event: 2078403
== CMSSW:  JetSpecific: MC Particle is invalid
== CMSSW:
== CMSSW: %MSG
== CMSSW: [WARNING] Category not found:
== CMSSW: 1 1   0.493362 0.493362   -3.40282e+38 -3.40282e+38   0 0
== CMSSW: [WARNING] Category not found:
== CMSSW: 1 1   1.62939 1.62939 -3.40282e+38 -3.40282e+38   0 0
== CMSSW:
== CMSSW:
== CMSSW: A fatal system signal has occurred: segmentation violation
== CMSSW: The following is the call stack containing the origin of the signal.
== CMSSW: NOTE:The first few functions on the stack are artifacts of processing the signal and can be ignored
== CMSSW:
== CMSSW: Thread 1 (Thread 0x2b1c57c747c0 (LWP 37498)):
== CMSSW: #0  0x00002b1c562220d3 in poll () from /lib64/libc.so.6
== CMSSW: #1  0x00002b1c59d5a844 in full_read.constprop () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_3/lib/slc6_amd64_gcc493/libFWCoreServices.so
== CMSSW: #2  0x00002b1c59d5aaac in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_3/lib/slc6_amd64_gcc493/libFWCoreServices.so
== CMSSW: #3  0x00002b1c59d5ac13 in sig_dostack_then_abort () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_3/lib/slc6_amd64_gcc493/libFWCoreServices.so
== CMSSW: #4  <signal handler called>
== CMSSW: #5  0x00002b1c7a024d20 in reco::makeSpecific(std::vector<edm::Ptr<reco::Candidate>, std::allocator<edm::Ptr<reco::Candidate> > > const&, reco::GenJet::Specific*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_3/lib/slc6_amd64_gcc493/libRecoJetsJetProducers.so
== CMSSW: #6  0x00002b1c7a0254f5 in reco::writeSpecific(reco::GenJet&, ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > const&, ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<double>, ROOT::Math::DefaultCoordinateSystemTag> const&, std::vector<edm::Ptr<reco::Candidate>, std::allocator<edm::Ptr<reco::Candidate> > > const&, edm::EventSetup const&) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_3/lib/slc6_amd64_gcc493/libRecoJetsJetProducers.so
== CMSSW: #7  0x00002b1c7d8b58c1 in PseudoTopProducer::produce(edm::Event&, edm::EventSetup const&) () from /wntmp/condor/execute/dir_3845/glide_HQyb2t/execute/dir_35381/CMSSW_7_6_3_patch2/lib/slc6_amd64_gcc493/pluginTopQuarkAnalysisTopEventProducers.so
== CMSSW: #8  0x00002b1c53ed22a9 in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventPrincipal&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_3/lib/slc6_amd64_gcc493/libFWCoreFramework.so
```

**Comment by jhgoh** [comment]
Resolved the problem. Fix to be made soon.

**Comment by jhgoh** [comment]
Solved. Merged in vallot:cmssw/cat76x
